const config = {
  prefix: ":",
  clientKey: "ODIyMDQ5MzAzMTMyMzcyOTky.YFMnEg.AJtWsRjZyUeuVb2NstA4xjtxJ44",
  clashApiToken:
    "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjIwNmVkZjJhLTYwZTUtNDgyMS1iOWFhLTNjZDU1YzUzNGE0ZiIsImlhdCI6MTYxNjA2NTYxMSwic3ViIjoiZGV2ZWxvcGVyL2IyZDU4ODJhLWU3NzktYWNjZi02ZTFmLWIyZGYyYjRlNTQyNCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEwMy4xOTMuMTk3Ljc3Il0sInR5cGUiOiJjbGllbnQifV19.Q_bjOiy09VrxX-45HbSqeGDdZDxxBdLvTQdHUSvPwX_JI2luqEcXEJLGdQieuRNdXBif6Pt4isDRofiztysoqQ",
};

export default config;
